### PR TITLE
fix: ignore colons after hash when correcting scp urls

### LINKED ISSUE #148: [BUG] since v4 `git@github.com:user/package-2#semver:^1.0.0` syntax is handled incorrectly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As of `8.1.2` of `npm-package-arg`, a particular style of git URL specifying a semver range gets misinterpreted as a `directory` type instead of `git`.

I narrowed it down to this commit: https://github.com/npm/npm-package-arg/commit/881f1c31d8411db9a3999ad5ee1d2552b334fb31 in which `hosted-git-info` was updated from v3 to v4.

Repro (using `npm-package-arg`):

**index.js**
```js
const npa = require("npm-package-arg");

// Incorrect as of 8.1.2 of npm-package-arg, which is v4 of hosted-git-info instead of v3
console.log(npa.resolve('package-2', 'git@github.com:user/package-2#semver:^1.0.0').type); // "directory"

// Correct

// (version range removed)
console.log(npa.resolve('package-2', 'git@github.com:user/package-2#semver').type); // "git"

// (alternative syntax for start of URL, version range still present)
console.log(npa.resolve('package-2', 'github:user/package-2#semver:^1.0.0').type); // "git"
console.log(npa.resolve('package-2', 'git+ssh://github.com:user/package-2#semver:^1.0.0').type); // "git"
console.log(npa.resolve('package-2', 'git://github.com:user/package-2#semver:^1.0.0').type); // "git"
```

### Expected Behavior

I expect to `git@github.com:user/package-2#semver:^1.0.0` be handled correctly by `hosted-git-info`

(therefore allowing `console.log(npa.resolve('package-2', 'git@github.com:user/package-2#semver:^1.0.0').type);` to correctly log "git")

### Steps To Reproduce

Create the index.js file as I provided above and run `node index.js`

### Environment

N/A

### PR DESCRIPTION
**Pull request by lukekarrys**
Fixes #148

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -189,12 +194,11 @@ const isGitHubShorthand = (arg) => {
...
 const correctUrl = (giturl) => {
   const firstAt = giturl.indexOf('@')
-  const lastHash = giturl.lastIndexOf('#')
-  let firstColon = giturl.indexOf(':')
-  let lastColon = giturl.lastIndexOf(':', lastHash > -1 ? lastHash : Infinity)
+  // ignore colons that come after the hash since that could include colons such as:
+  // git@github.com:user/package-2#semver:^1.0.0
+  const lastColonBeforeHash = lastIndexOfBefore(giturl, ':', '#')
 
-  let corrected
```
Comment (lukekarrys) [inline lib/index.js:196]: I removed the `corrected` variable declaration because we were assigning to it in the first `if` block but then not guarding against it in the second `if` block despite using it there. So it's effectively the same as mutating `giturl`.

File: test/github.js [hunk 2]
```diff
@@ -31,157 +31,158 @@ const valid = {
   //
   // NOTE these do not accept auth at all
   'foo/bar': { ...defaults, default: 'shortcut' },
-  'foo/bar#branch': { ...defaults, default: 'shortcut', committish: 'branch' },
+  'foo/bar#branch:^1.0.0': { ...defaults, default: 'shortcut', committish: 'branch:^1.0.0' },
```
Comment (lukekarrys) [inline test/github.js:34]: Since the original bug reported in #148 was only present in some urls, I replaced all `committish` assertions with a semver looking branch name to be sure I caught any other code paths that might have had a similar problem. I don't think anything is lost by using this in all cases.

Comment (wraithgar) [reply test/github.js:34]: Are there other special characters in branches we want to enforce regression testing on? `/`?

**Review by wraithgar — APPROVED** [review]
Approved with a take-it-or-leave-it suggestion for branch names in tests.

File: test/github.js (hunk 2 above)
Comment (lukekarrys) [reply test/github.js]: Good call on this. `@` is valid in branches and we were breaking on those too.
